# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: confible

before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    id: "confible"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - id: confible
    builds:
    - confible
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next-{{.Commit}}"

nfpms:
  - maintainer: Simon Jürgensmeyyer <simon.juergensmeyer@gmail.com>
    homepage: https://github.com/sj14/confible/
    description: Confible is a simple configuration tool for your local machine.
    license: MIT
    formats:
      - deb
      - rpm
    builds:
      - confible


brews:
  - name: confible
    ids:
      - confible
    tap:
      owner: sj14
      name: homebrew-tap
    description: Confible is a simple configuration tool for your local machine.

release:
  github:
    owner: sj14
    name: confible
  disable: false
  draft: false
  prerelease: false

changelog:
  filters:
    exclude:
      - typo
