# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: confible

before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next-{{.Commit}}"
brews:
  - name: confible
    skip_upload: auto
    tap:
      owner: sj14
      name: homebrew-tap
    description: Confible is a simple configuration tool for your local machine.

release:
  github:
    owner: sj14
    name: confible
  disable: false
  draft: false
  prerelease: auto
changelog:
  filters:
    exclude:
      - typo
