[settings]
id = "config"

[[config]]
priority = 200
path = "testfiles/config.txt"
#truncate = true
comment_symbol = "#"
append = """
my_key=42
my_key=43
my_key=44

My User is: {{ .Env.USER }}
"""

[[config]]
priority = 200
path = "testfiles/config.txt"
comment_symbol = "#"
append = """
test2
"""

[[config]]
priority = 500
path = "testfiles/config2.txt"
comment_symbol = "#"
append = """
test2
"""
