# [[commands]]
# command = "brew version"

[[commands]]
commands = [
    "brew --version",
    "echo yo",
]

[[configs]]
target = "testfiles/testfile"
comment_symbol = "#"
append = """
my_key=42
my_key=43
my_key=44
"""

[[configs]]
target = "testfiles/testfile2"
comment_symbol = "§§§"
append = """
my_key=421
my_key=431
my_key=441
"""