id = "file2"

[[commands]]
exec = [
    'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"',
    "echo yoyo",
]

[[config]]
path = "testfiles/testfile"
#truncate = true
comment_symbol = "#"
append = """
my_key=42
my_key=43
my_key=44
"""

[[config]]
path = "testfiles/testfile"
comment_symbol = "$$$"
append = """
your_key=421
your_kEy=431
your_key=441
"""

[[config]]
path = "testfiles/testfile2"
comment_symbol = "$$$"
append = """
our_key=5421
our_key=5431
our_key=5441
"""

[[config]]
path = "testfiles/testfile_truncate"
truncate = true
comment_symbol = "#"
append = """
my_key=42
my_key=43
my_key=44
"""
