
[[commands]]
exec = [
    "echo yo", 
    "echo yoyo",
]

[[configs]]
target = "testfiles/testfile"
comment_symbol = "#"
append = """
my_key=42
my_key=43
my_key=44
"""

[[configs]]
target = "testfiles/testfile"
comment_symbol = "$$$"
append = """
your_key=421
your_kEy=431
your_key=441
"""


[[configs]]
target = "testfiles/testfile2"
comment_symbol = "$$$"
append = """
our_key=5421
our_key=5431
our_key=5441
"""
