[[commands]]
name = "test commands"
exec = [
    'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"',
    "echo yoyo",
]

[[config]]
name = "testfile 1"
path = "testfiles/testfile"
#truncate = true
comment_symbol = "#"
append = """
my_key=42
my_key=43
my_key=44
"""

[[config]]
name = "testfile 1x2"
path = "testfiles/testfile"
comment_symbol = "$$$"
append = """
your_key=421
your_kEy=431
your_key=441
"""

[[config]]
name = "testfile 2"
path = "testfiles/testfile2"
comment_symbol = "$$$"
append = """
our_key=5421
our_key=5431
our_key=5441
"""

[[config]]
name = "testfile truncate"
path = "testfiles/testfile_truncate"
truncate = true
comment_symbol = "#"
append = """
my_key=42
my_key=43
my_key=44
"""