id = "variables"

[[variables]]
input = [
    { var = "nick", prompt = "your nick name" },
    { var = "age", prompt = "your age in years" },
]
exec = [
    { var = "curDate", cmd = "date" },
    { var = "something", cmd = "echo 'Hello World!'" },
]

[[config]]
path = "testfiles/variables.txt"
#truncate = true
comment_symbol = "#"
append = """
My User is: {{ .Env.USER }}
My Nick is {{ .Var.nick}}
I am {{ .Var.age}} years old
Today is {{ .Var.curDate }}
I want to say {{ .Var.something }}

"""
