id = "variables"

[[variables]]
input = [
    ["nick", "your nick name"],
    ["age", "your age in years"],
]
exec = [
    ["curDate", "date"],
    ["something", "echo 'Hello World'"],
]

[[config]]
path = "testfiles/variables"
#truncate = true
comment_symbol = "#"
append = """
My User is: {{ .Env.USER }}
My Nick is {{ .Var.nick}}
I am {{ .Var.age}} years old
Today is {{ .Var.curDate }}
I want to say {{ .Var.something }}

"""
